"""add is_admin to user model

Revision ID: 303bdb014234
Revises: 4c31fe045eae
Create Date: 2024-04-22 08:50:53.221475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303bdb014234'
down_revision = '4c31fe045eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
