"""modified user

Revision ID: cf2c4af5a52c
Revises: 343b5680a530
Create Date: 2024-04-26 08:51:18.938387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2c4af5a52c'
down_revision = '343b5680a530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.drop_column('is_manager')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manager', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
