"""added investment column to transaction tabl

Revision ID: db1bb042cc8a
Revises: 02b5e2725438
Create Date: 2024-05-11 17:13:57.763970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1bb042cc8a'
down_revision = '02b5e2725438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('investment')

    # ### end Alembic commands ###
